name: Build Label Printer App

# 触发规则：手动触发
on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version Tag (e.g., v1.0.1)'
        required: true
        default: 'v1.0.0'

# 权限设置：允许发布 Release 和 删除旧记录
permissions:
  contents: write
  actions: write

jobs:
  build_and_release:
    # 假设您的代码需要 Windows 环境
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- 关键修改：设置工作目录为 LabelPrinterApp/ ---
    # 所有后续 run 命令都将在这个目录下执行
    - name: Change working directory to LabelPrinterApp
      run: |
        echo "Moving into the LabelPrinterApp directory for execution."
        cd LabelPrinterApp
        # 在 Windows runner 上，将工作目录设置为环境变量，以便后续步骤使用
        echo "WORKING_DIR=LabelPrinterApp" >> $GITHUB_ENV
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' # 保持 Win7 兼容
        architecture: 'x64'

    - name: Install dependencies
      # 确保 run 命令是在新的工作目录下运行的
      run: |
        python -m pip install --upgrade pip
        # 假设 requirements.txt 在 LabelPrinterApp/ 目录下
        pip install -r requirements.txt
        pip install pyinstaller
      working-directory: ${{ env.WORKING_DIR }} # 使用工作目录环境变量

    - name: Update Version File
      shell: python
      # 确保 run 命令是在新的工作目录下运行的
      run: |
        # 因为已切换到 LabelPrinterApp 目录，所以路径从 src/ 开始
        import os
        version = "${{ inputs.version_tag }}"
        try:
            with open('src/version.py', 'w') as f:
                f.write(f'APP_VERSION = "{version}"\n')
        except FileNotFoundError:
            os.makedirs('src', exist_ok=True)
            with open('src/version.py', 'w') as f:
                f.write(f'APP_VERSION = "{version}"\n')
      working-directory: ${{ env.WORKING_DIR }}

    - name: Build with PyInstaller
      # 确保 run 命令是在新的工作目录下运行的
      run: |
        # 打包为单个 EXE 文件
        # 如果 assets/icon.ico 不存在，请删除 --icon 参数
        # 如果 assets 文件夹为空，请删除 --add-data 参数
        # main.py 相对路径：在 LabelPrinterApp 目录下
        pyinstaller --noconfirm --onefile --windowed --name "LabelPrinter" --icon "assets/icon.ico" --add-data "assets;assets" main.py
      working-directory: ${{ env.WORKING_DIR }}

    # 步骤 1: 上传到构建产物 (Artifacts) - 作为备份
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LabelPrinter-${{ inputs.version_tag }}
        # path 需要是相对于仓库根目录的路径
        path: LabelPrinterApp/dist/LabelPrinter.exe

    # 步骤 2: 发布到 Releases 页面 (正式发布)
    - name: Create Release
      uses: softprops/action-gh-release@v1
      # 只有当手动输入了 version_tag 时才运行
      if: inputs.version_tag != ''
      with:
        tag_name: ${{ inputs.version_tag }}
        name: Release ${{ inputs.version_tag }}
        # files 需要是相对于仓库根目录的路径
        files: LabelPrinterApp/dist/LabelPrinter.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    runs-on: ubuntu-latest
    needs: build_and_release
    steps:
    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 3 # 已修改：只保留最近 3 条记录
